// Code generated by entc, DO NOT EDIT.

package mailbox

const (
	// Label holds the string label denoting the mailbox type in the database.
	Label = "mail_box"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the mailbox in the database.
	Table = "mail_boxes"
)

// Columns holds all SQL columns for mailbox fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
