// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/notification/pkg/db/ent/mailbox"
)

// MailBoxCreate is the builder for creating a MailBox entity.
type MailBoxCreate struct {
	config
	mutation *MailBoxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// Mutation returns the MailBoxMutation object of the builder.
func (mbc *MailBoxCreate) Mutation() *MailBoxMutation {
	return mbc.mutation
}

// Save creates the MailBox in the database.
func (mbc *MailBoxCreate) Save(ctx context.Context) (*MailBox, error) {
	var (
		err  error
		node *MailBox
	)
	if len(mbc.hooks) == 0 {
		if err = mbc.check(); err != nil {
			return nil, err
		}
		node, err = mbc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MailBoxMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mbc.check(); err != nil {
				return nil, err
			}
			mbc.mutation = mutation
			if node, err = mbc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(mbc.hooks) - 1; i >= 0; i-- {
			if mbc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mbc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mbc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mbc *MailBoxCreate) SaveX(ctx context.Context) *MailBox {
	v, err := mbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mbc *MailBoxCreate) Exec(ctx context.Context) error {
	_, err := mbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mbc *MailBoxCreate) ExecX(ctx context.Context) {
	if err := mbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mbc *MailBoxCreate) check() error {
	return nil
}

func (mbc *MailBoxCreate) sqlSave(ctx context.Context) (*MailBox, error) {
	_node, _spec := mbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mbc *MailBoxCreate) createSpec() (*MailBox, *sqlgraph.CreateSpec) {
	var (
		_node = &MailBox{config: mbc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: mailbox.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: mailbox.FieldID,
			},
		}
	)
	_spec.OnConflict = mbc.conflict
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MailBox.Create().
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (mbc *MailBoxCreate) OnConflict(opts ...sql.ConflictOption) *MailBoxUpsertOne {
	mbc.conflict = opts
	return &MailBoxUpsertOne{
		create: mbc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MailBox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mbc *MailBoxCreate) OnConflictColumns(columns ...string) *MailBoxUpsertOne {
	mbc.conflict = append(mbc.conflict, sql.ConflictColumns(columns...))
	return &MailBoxUpsertOne{
		create: mbc,
	}
}

type (
	// MailBoxUpsertOne is the builder for "upsert"-ing
	//  one MailBox node.
	MailBoxUpsertOne struct {
		create *MailBoxCreate
	}

	// MailBoxUpsert is the "OnConflict" setter.
	MailBoxUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MailBox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *MailBoxUpsertOne) UpdateNewValues() *MailBoxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.MailBox.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *MailBoxUpsertOne) Ignore() *MailBoxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MailBoxUpsertOne) DoNothing() *MailBoxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MailBoxCreate.OnConflict
// documentation for more info.
func (u *MailBoxUpsertOne) Update(set func(*MailBoxUpsert)) *MailBoxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MailBoxUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *MailBoxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MailBoxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MailBoxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MailBoxUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MailBoxUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MailBoxCreateBulk is the builder for creating many MailBox entities in bulk.
type MailBoxCreateBulk struct {
	config
	builders []*MailBoxCreate
	conflict []sql.ConflictOption
}

// Save creates the MailBox entities in the database.
func (mbcb *MailBoxCreateBulk) Save(ctx context.Context) ([]*MailBox, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mbcb.builders))
	nodes := make([]*MailBox, len(mbcb.builders))
	mutators := make([]Mutator, len(mbcb.builders))
	for i := range mbcb.builders {
		func(i int, root context.Context) {
			builder := mbcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailBoxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = mbcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mbcb *MailBoxCreateBulk) SaveX(ctx context.Context) []*MailBox {
	v, err := mbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mbcb *MailBoxCreateBulk) Exec(ctx context.Context) error {
	_, err := mbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mbcb *MailBoxCreateBulk) ExecX(ctx context.Context) {
	if err := mbcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MailBox.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (mbcb *MailBoxCreateBulk) OnConflict(opts ...sql.ConflictOption) *MailBoxUpsertBulk {
	mbcb.conflict = opts
	return &MailBoxUpsertBulk{
		create: mbcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MailBox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (mbcb *MailBoxCreateBulk) OnConflictColumns(columns ...string) *MailBoxUpsertBulk {
	mbcb.conflict = append(mbcb.conflict, sql.ConflictColumns(columns...))
	return &MailBoxUpsertBulk{
		create: mbcb,
	}
}

// MailBoxUpsertBulk is the builder for "upsert"-ing
// a bulk of MailBox nodes.
type MailBoxUpsertBulk struct {
	create *MailBoxCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MailBox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *MailBoxUpsertBulk) UpdateNewValues() *MailBoxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MailBox.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *MailBoxUpsertBulk) Ignore() *MailBoxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MailBoxUpsertBulk) DoNothing() *MailBoxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MailBoxCreateBulk.OnConflict
// documentation for more info.
func (u *MailBoxUpsertBulk) Update(set func(*MailBoxUpsert)) *MailBoxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MailBoxUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *MailBoxUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MailBoxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MailBoxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MailBoxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
