// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/notification/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/notification/pkg/db/ent/readuser"
	"github.com/google/uuid"
)

// ReadUserQuery is the builder for querying ReadUser entities.
type ReadUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ReadUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReadUserQuery builder.
func (ruq *ReadUserQuery) Where(ps ...predicate.ReadUser) *ReadUserQuery {
	ruq.predicates = append(ruq.predicates, ps...)
	return ruq
}

// Limit adds a limit step to the query.
func (ruq *ReadUserQuery) Limit(limit int) *ReadUserQuery {
	ruq.limit = &limit
	return ruq
}

// Offset adds an offset step to the query.
func (ruq *ReadUserQuery) Offset(offset int) *ReadUserQuery {
	ruq.offset = &offset
	return ruq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ruq *ReadUserQuery) Unique(unique bool) *ReadUserQuery {
	ruq.unique = &unique
	return ruq
}

// Order adds an order step to the query.
func (ruq *ReadUserQuery) Order(o ...OrderFunc) *ReadUserQuery {
	ruq.order = append(ruq.order, o...)
	return ruq
}

// First returns the first ReadUser entity from the query.
// Returns a *NotFoundError when no ReadUser was found.
func (ruq *ReadUserQuery) First(ctx context.Context) (*ReadUser, error) {
	nodes, err := ruq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{readuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ruq *ReadUserQuery) FirstX(ctx context.Context) *ReadUser {
	node, err := ruq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReadUser ID from the query.
// Returns a *NotFoundError when no ReadUser ID was found.
func (ruq *ReadUserQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ruq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{readuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ruq *ReadUserQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := ruq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReadUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReadUser entity is found.
// Returns a *NotFoundError when no ReadUser entities are found.
func (ruq *ReadUserQuery) Only(ctx context.Context) (*ReadUser, error) {
	nodes, err := ruq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{readuser.Label}
	default:
		return nil, &NotSingularError{readuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ruq *ReadUserQuery) OnlyX(ctx context.Context) *ReadUser {
	node, err := ruq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReadUser ID in the query.
// Returns a *NotSingularError when more than one ReadUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (ruq *ReadUserQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = ruq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{readuser.Label}
	default:
		err = &NotSingularError{readuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ruq *ReadUserQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := ruq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReadUsers.
func (ruq *ReadUserQuery) All(ctx context.Context) ([]*ReadUser, error) {
	if err := ruq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ruq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ruq *ReadUserQuery) AllX(ctx context.Context) []*ReadUser {
	nodes, err := ruq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReadUser IDs.
func (ruq *ReadUserQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := ruq.Select(readuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ruq *ReadUserQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := ruq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ruq *ReadUserQuery) Count(ctx context.Context) (int, error) {
	if err := ruq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ruq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ruq *ReadUserQuery) CountX(ctx context.Context) int {
	count, err := ruq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ruq *ReadUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := ruq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ruq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ruq *ReadUserQuery) ExistX(ctx context.Context) bool {
	exist, err := ruq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReadUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ruq *ReadUserQuery) Clone() *ReadUserQuery {
	if ruq == nil {
		return nil
	}
	return &ReadUserQuery{
		config:     ruq.config,
		limit:      ruq.limit,
		offset:     ruq.offset,
		order:      append([]OrderFunc{}, ruq.order...),
		predicates: append([]predicate.ReadUser{}, ruq.predicates...),
		// clone intermediate query.
		sql:    ruq.sql.Clone(),
		path:   ruq.path,
		unique: ruq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReadUser.Query().
//		GroupBy(readuser.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ruq *ReadUserQuery) GroupBy(field string, fields ...string) *ReadUserGroupBy {
	grbuild := &ReadUserGroupBy{config: ruq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ruq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ruq.sqlQuery(ctx), nil
	}
	grbuild.label = readuser.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.ReadUser.Query().
//		Select(readuser.FieldAppID).
//		Scan(ctx, &v)
//
func (ruq *ReadUserQuery) Select(fields ...string) *ReadUserSelect {
	ruq.fields = append(ruq.fields, fields...)
	selbuild := &ReadUserSelect{ReadUserQuery: ruq}
	selbuild.label = readuser.Label
	selbuild.flds, selbuild.scan = &ruq.fields, selbuild.Scan
	return selbuild
}

func (ruq *ReadUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ruq.fields {
		if !readuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ruq.path != nil {
		prev, err := ruq.path(ctx)
		if err != nil {
			return err
		}
		ruq.sql = prev
	}
	return nil
}

func (ruq *ReadUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReadUser, error) {
	var (
		nodes = []*ReadUser{}
		_spec = ruq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*ReadUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &ReadUser{config: ruq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ruq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ruq *ReadUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ruq.querySpec()
	_spec.Node.Columns = ruq.fields
	if len(ruq.fields) > 0 {
		_spec.Unique = ruq.unique != nil && *ruq.unique
	}
	return sqlgraph.CountNodes(ctx, ruq.driver, _spec)
}

func (ruq *ReadUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ruq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ruq *ReadUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   readuser.Table,
			Columns: readuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: readuser.FieldID,
			},
		},
		From:   ruq.sql,
		Unique: true,
	}
	if unique := ruq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ruq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, readuser.FieldID)
		for i := range fields {
			if fields[i] != readuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ruq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ruq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ruq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ruq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ruq *ReadUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ruq.driver.Dialect())
	t1 := builder.Table(readuser.Table)
	columns := ruq.fields
	if len(columns) == 0 {
		columns = readuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ruq.sql != nil {
		selector = ruq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ruq.unique != nil && *ruq.unique {
		selector.Distinct()
	}
	for _, p := range ruq.predicates {
		p(selector)
	}
	for _, p := range ruq.order {
		p(selector)
	}
	if offset := ruq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ruq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReadUserGroupBy is the group-by builder for ReadUser entities.
type ReadUserGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rugb *ReadUserGroupBy) Aggregate(fns ...AggregateFunc) *ReadUserGroupBy {
	rugb.fns = append(rugb.fns, fns...)
	return rugb
}

// Scan applies the group-by query and scans the result into the given value.
func (rugb *ReadUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rugb.path(ctx)
	if err != nil {
		return err
	}
	rugb.sql = query
	return rugb.sqlScan(ctx, v)
}

func (rugb *ReadUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rugb.fields {
		if !readuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rugb *ReadUserGroupBy) sqlQuery() *sql.Selector {
	selector := rugb.sql.Select()
	aggregation := make([]string, 0, len(rugb.fns))
	for _, fn := range rugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rugb.fields)+len(rugb.fns))
		for _, f := range rugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rugb.fields...)...)
}

// ReadUserSelect is the builder for selecting fields of ReadUser entities.
type ReadUserSelect struct {
	*ReadUserQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rus *ReadUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rus.prepareQuery(ctx); err != nil {
		return err
	}
	rus.sql = rus.ReadUserQuery.sqlQuery(ctx)
	return rus.sqlScan(ctx, v)
}

func (rus *ReadUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rus.sql.Query()
	if err := rus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
