// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/notification/pkg/db/ent/readstate"
)

// ReadState is the model entity for the ReadState schema.
type ReadState struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReadState) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case readstate.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ReadState", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReadState fields.
func (rs *ReadState) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case readstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rs.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this ReadState.
// Note that you need to call ReadState.Unwrap() before calling this method if this ReadState
// was returned from a transaction, and the transaction was committed or rolled back.
func (rs *ReadState) Update() *ReadStateUpdateOne {
	return (&ReadStateClient{config: rs.config}).UpdateOne(rs)
}

// Unwrap unwraps the ReadState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rs *ReadState) Unwrap() *ReadState {
	tx, ok := rs.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReadState is not a transactional entity")
	}
	rs.config.driver = tx.drv
	return rs
}

// String implements the fmt.Stringer.
func (rs *ReadState) String() string {
	var builder strings.Builder
	builder.WriteString("ReadState(")
	builder.WriteString(fmt.Sprintf("id=%v", rs.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ReadStates is a parsable slice of ReadState.
type ReadStates []*ReadState

func (rs ReadStates) config(cfg config) {
	for _i := range rs {
		rs[_i].config = cfg
	}
}
