// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// MailBox is the predicate function for mailbox builders.
type MailBox func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// ReadState is the predicate function for readstate builders.
type ReadState func(*sql.Selector)
